name: Python Tests and Coverage

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Versão do Python usada para todos os testes

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage check
        run: |
          pytest --cov --cov-report=xml --cov-fail-under=70

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.os == 'ubuntu-latest' }} # Dispara o Codecov apenas após os testes em Ubuntu
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
